# Generated by Django 2.2.6 on 2019-11-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restuarant',
            new_name='Car',
        ),
    ]
